### ISSUE TITLE
Error When A Bolt Subscribing To Multiple Streams From Other Bolts / Spouts

### ISSUE THREAD

**Issue by SanthoshPrasad** [ptgoetz/flux#15]
Hi Taylor,

You can find more information on the specified error below.

**Stream Definition**

name: Cosnumer2---->Aggregator
  from: Cosnumer2
  to: Aggregator
  grouping:
    streamId: Cosnumer2_Aggregator
    type: SHUFFLE

name: Consumer1---->Aggregator
  from: Consumer1
  to: Aggregator
  grouping:
    streamId: Consumer1_Aggregator
    type: SHUFFLE

**Stack Trace**

Exception in thread "main" java.lang.IllegalArgumentException: Bolt has already been declared for id Aggregator
    at backtype.storm.topology.TopologyBuilder.validateUnusedId(TopologyBuilder.java:212)
    at backtype.storm.topology.TopologyBuilder.setBolt(TopologyBuilder.java:139)
    at backtype.storm.topology.TopologyBuilder.setBolt(TopologyBuilder.java:171)
    at org.apache.storm.flux.FluxBuilder.buildStreamDefinitions(FluxBuilder.java:162)
    at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:94)
    at org.apache.storm.flux.Flux.runCli(Flux.java:153)
    at org.apache.storm.flux.Flux.main(Flux.java:98)

*\* I made few changes to handle this scenario in my forked repo: [here](https://github.com/SanthoshPrasad/flux)
 it's working, please review it once, if possible *\* 

Thank you.

**Comment by ptgoetz** [comment]
Hi @SanthoshPrasad,

Flux is not incorporated with Apache Storm, so any bugs/issues should be posted there. And actually this very issue has already come up and been addressed in Apache Storm 0.10.0-beta1.
