### ISSUE TITLE
Configure a configMethod that takes no arguments

### ISSUE THREAD

**Issue by ashnazg** [ptgoetz/flux#17]
Can the configMethod implementation handle calling a method that requires no arguments?  If so, I cannot figure out how to write that in the YAML.

```
configMethods
- name: "myMethod"
```

does not work:

```
Exception in thread "main" java.lang.NullPointerException
    at org.apache.storm.flux.FluxBuilder.findCompatibleMethod(FluxBuilder.java:445)
    at org.apache.storm.flux.FluxBuilder.invokeConfigMethods(FluxBuilder.java:424)
    at org.apache.storm.flux.FluxBuilder.buildObject(FluxBuilder.java:302)
    at org.apache.storm.flux.FluxBuilder.buildComponents(FluxBuilder.java:339)
    at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:75)
    at org.apache.storm.flux.Flux.runCli(Flux.java:153)
    at org.apache.storm.flux.Flux.main(Flux.java:98)
```

```
configMethods
- name: "myMethod"
  args:
```

does not work:

```
...
Caused by: java.lang.NullPointerException
    at org.apache.storm.flux.model.ConfigMethodDef.setArgs(ConfigMethodDef.java:45)
```

```
configMethods
- name: "myMethod"
  args: []
```

does not work:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to find configuration method 'build' in class 'io.latent.storm.rabbitmq.config.ConsumerConfigBuilder' with arguments [].
    at org.apache.storm.flux.FluxBuilder.invokeConfigMethods(FluxBuilder.java:431)
    at org.apache.storm.flux.FluxBuilder.buildObject(FluxBuilder.java:302)
    at org.apache.storm.flux.FluxBuilder.buildComponents(FluxBuilder.java:339)
    at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:75)
    at org.apache.storm.flux.Flux.runCli(Flux.java:153)
    at org.apache.storm.flux.Flux.main(Flux.java:98)
```

(presumably because this results in usage of `build( empty list)` rather than just `build()`)

**Comment by ashnazg** [comment]
Just saw the "migrated to" notice in the README.  Reopened this as a Question in JIRA (https://issues.apache.org/jira/browse/STORM-1126).
